### ISSUE TITLE
Trouble installing on Krita 4.2.8

### ISSUE THREAD

**Issue by losfroger** [GDQuest/krita-batch-exporter#33]
Hi, I've been having some trouble with installing this plugin. I'm using windows 10, krita version 4.2.8, python 3.8.1 (64 bits) and installed Pillow.

The problem is that when I put the krita_batch_exporter folder and the .desktop file it appears in Krita but it appears greyed out and the docker isn't in the docker list. I don't know if I'm missing something, but I've tried installing both the alpha build and the current master branch

**Comment by NathanLovato** [comment]
You probably don't have the Pillow imaging library installed. You need a version of Pillow that's specific to your OS, architecture, and version of the python interpreter in Krita. You can find the wheel files (python package installers) there: https://pypi.org/project/Pillow/#files

You need to install the correct version in a `Dependencies` directory in the addon with `pip3 install --target`. The path is different depending on your computer but for me it's:

```
pip3 install --target="/home/gdquest/.local/share/krita/pykrita/krita-batch-exporter/Dependencies" https://files.pythonhosted.org/packages/dc/bd/ba64273d3fdeb68c74b040e3e42f5a3c2f643e8e65b0b1ad0b18425ed67a/Pillow-6.2.1-cp35-cp35m-manylinux1_x86_64.whl
```

We haven't written detailed install instructions because we've contributed it to Krita, so Pillow comes preinstalled in a future Krita release. My teammate Razvan wrote the code to install Pillow on Linux, now we're waiting for someone to test it on Mac and Windows.

**Comment by losfroger** [comment]
Hi, thanks for your reply! But it's still being greyed out in Krita.

I installed Pillow following your instructions with the following command (the directory path is incomplete here)
```
pip3 install --target="C:...\krita\pykrita\krita_batch_exporter\Dependencies" https://files.pythonhosted.org/packages/40/3f/db380908cc908db30e3defd09a73b27de5e9da45e09b090ccb0ab251826c/Pillow-6.2.1-cp27-cp27m-win_amd64.whl
```

After installing Pillow, now my file tree looks as follows:
- pykrita
  - krita_batch_exporter.desktop
  - krita_batch_exporter (folder)
    - ``__pycache__`` (folder)
    - Dependencies (folder)
      - PIL (folder)
      - Pillow-6.2.1.dist-info (folder)
    - Utils (folder)
    - All the other files from the plugin

I also tried using:
```
pip3 install --target="C:...\krita\pykrita\krita_batch_exporter\Dependencies" Pillow
```

But the result is the same and the plugin is stil greyed out, I don't know if this could be a Windows problem or if I'm still missing something.

**Comment by razcore-art** [comment]
@losfroger, you need to follow the steps here: https://docs.krita.org/en/user_manual/python_scripting/introduction_to_python_scripting.html#how-to-enable-the-scripter-plugin to turn on the Scripter Plugin if it isn't enabled. Open it up by going to `Tools ‣ Scripts ‣ Scripter` and run this: `import sys; print(sys.version)` and chech the Python version that Krita uses. It will probably be 3.5 or 3.7 or something of that sorts. That's the version of Pillow you need to install - the `cp27`, `cp37` part of the filename when downloading the `.whl` file.

**Comment by losfroger** [comment]
@razcore-art thank you so much, that actually solved my problem! I just had to get the python version as you said and get the specific version.
